server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kevcherrington/config_repo.git